### ISSUE TITLE
Basic CRUD for Knative Functions in Console UI 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1277]
**Description**

Provide an optional microforntend that would allow UI access to knative functions:

 - Create function in modal window(essential data only)
 - List functions
 - See and edit details

**Reasons**

Provide UI access to knative based functions

-----
 - [ ]  design minimalistic flow : Create function in modal, list functions, inspect & edit function basic details
 - [ ]  design gql API for creating knative based function 
 - [ ]  implement mocked gql - (optional) 
 - [ ]  implement react based micro UI  
 - [ ]  implement  gql based on knative function controller
