### ISSUE TITLE
Support API Packages in Compass UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1557]
**Description**

Support an additional layer (package) in the application Ui in compass.
A group of API (rest or async mixed) definitions form a package. A group of packages forms an application.

Enable this extra layer in the hierarchy (application - **package(s)** - apis) in the Compass UI
Provide a way to define API packages for an application. Allow to define Rest and Async APIs within a package only.

Authentication credentials will need to be moved from API to API package layer.

**AC**

 - [x] As a user I can create an API package for a given application (providing name, description and json schema (as input in text area) defining authorisation data
 - [x] For a given API package I can  edit default auth data
 - [ ] For a given API package I can define new Rest and Async API definitions ( as it was possible on application level)

**Reasons**

There might be some use cases that APIs are bundled into groups (packages) and accessible under one authorisation grant.

**Todos (can be grouped/divided further into tasks)**
* Don't allow user to provide / read API credentials, as it should be done in API Package context.
* Replace APIs & Events on application details view with API Packages list (with CR_D actions)
* Create API Package details view with (readonly) auth, API and Event lists (_RUD actions for API Package)
* Make sure that already used queries and mutations follow the new hierarchy (APIs and Events as a children of API package, not an application)
* After completion of the tasks above, inform X-Team so that `deprecated` GQL schema features can be safely removed ([example](https://github.com/kyma-incubator/compass/blob/master/components/director/pkg/graphql/schema.graphql#L147)).

**Attachments**

(ui mocks to be designed)

**Comment by Wawrzyn321** [comment]
Please note that user won't be able to provide the package credentials anymore (as it worked in case of APIs). The credentials are to be displayed as a readonly list on a package details view.
