### ISSUE TITLE
Support paging when listing runtimes in compass UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1650]
**Description**

Support paging when listing runtimes in compass UI

**Reasons**

In case there are more than 100 runtimes, the UI shows only the first 100.

**TODO**
- [x] Add pagination to runtimes view - https://github.com/kyma-project/console/pull/1684
- [x] Sort runtimes on the list by name  - https://github.com/kyma-incubator/compass/pull/1129
- [x] Bump - https://github.com/kyma-project/kyma/pull/7976

**Comment by kwiatekus** [comment]
Fixed with https://github.com/kyma-project/console/pull/1684
