### ISSUE TITLE
Apply Fiori Fundamentals. Phase 2 [Table-related]

### ISSUE THREAD

**Issue by marynaKhromova** [kyma-project/console#563]
**Todo**

---
**Tasks taken**
--

@maxmarkus - *to review* - https://github.com/jesusreal/console/pull/65
- [x] Rework grid panel with table. See comment [here](https://github.com/jesusreal/console/pull/51#discussion_r255467994), consider using table without header (eg in Namespace >  Secrets > Details
- [x] Refactor tables which are not from generic list using new classes for column width
- [x] Remove "Actions" from last cell on tables
- [x] Apply improved role design: <img width="470" src="https://user-images.githubusercontent.com/1720843/53750753-e93d9380-3eaa-11e9-83e6-704d1a656bc9.png">
- [x] Actions in tables should be right-aligned
- [x] Lambdas has empty dropdowns. Eg if Secret does not exist, or no Service is being found. Should be set to disabled state, design:  <img width="470" alt="disabled dropdown design" src="https://user-images.githubusercontent.com/1720843/53730350-f8571e00-3e77-11e9-8e96-31afbd54a880.png">

@marynaKhromova 
- [x] Headlines that belong to a table should be part of the panel consisting the panel (Namespace Details > Connected Applications)
- [x] Generic list plain table entries should not have `.fd-link` classes (namespace > services)
- [x] Namespace > services - "Internal Endpoints" should have less width
- [x] List columns should be word-breaked: Status, Age
- [x] Global Permissions - should have headline in panel header, upper pagination should be removed
- [x] Remove `.fd-form__control` from inputs and add `fd-form-control` instead (issues concerns 3 modals: `role-binding-modal` , `create-remote-environment-modal` , `create-preset-modal`)

**Comment by y-kkamil** [comment]
Also to be fixed (as it is not in line with fundamentals): cursor style on '...' element in generic list paging is set to 'pointer', but should be a 'default'.

**Comment by dariadomagala** [comment]
Service details view:
![Screen Shot 2019-02-19 at 13.58.59.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/6b432496-fc12-406e-90c1-073252472a7c)
Wouldn't that be better so those panels on the left side have the same height as those on the right?

**Comment by marynaKhromova** [comment]
The PR for @marynaKhromova part is https://github.com/jesusreal/console/pull/66
