### ISSUE TITLE
Adjust style of components that renders specifications so they are consistent with each other

### ISSUE THREAD

**Issue by derberg** [kyma-project/console#684]
**Description**

- Customize OpenAPI rendering component https://github.com/swagger-api/swagger-ui/blob/master/docs/customization/custom-layout.md
- Adjust existing AsyncAPI and OData components that we own
- Follow https://github.com/SAP/fundamental

**Reasons**

Best experience of the user is not only if all the features are available in the context, but also if they all are consistently following feel&look of entire Web site. This is why we should make sure that the open source component that we integrated in the Console, to render OpenAPI, is consistent in style with the rest of the UI

**Attachments**

How it looks like now in Console UI in Catalog view:
![image (7)](https://user-images.githubusercontent.com/6995927/54260825-5cf63500-456a-11e9-9640-c695ce6797b0.png)

This is how it will look like:

OData:
<img width="622" alt="Screen Shot 2019-05-19 at 08 42 16" src="https://user-images.githubusercontent.com/6995927/57978657-1b728200-7a12-11e9-9ee9-cb6aa7b7218f.png">

OpenAPI:
![Kyma_Catalog_API-Specs_Header_General-Infos](https://user-images.githubusercontent.com/6995927/57978663-2d542500-7a12-11e9-9483-12cec2a77d94.png)

AsyncAPI:
![Screen Shot 2019-08-05 at 12 47 13](https://user-images.githubusercontent.com/6995927/62459252-32a64d80-b77f-11e9-804f-9f8865118240.png)

**Comment by derberg** [comment]
@jasiu001 you sure you connected a correct issue to your pull request?

**Comment by derberg** [comment]
what left is:
- restyle OData and move it to documentation-component repo
- restyle of asyncapi will be done later once we start working on asyncapi-react component

**Comment by derberg** [comment]
as stated in above comment, asyncapi restyling in not in scope for 1.4, it is scheduled for 1.5

**Comment by derberg** [comment]
Update to info of the scope:
- support new styling and make sure it is integrated with the documentation-component and catalog views
- validator/parser as a props
- remove styled-components
- improve error handling to not stop the rendering + display error in UI (have a flag to disable UI errors) 
- remove playground from asnycapi-react and contribute to https://playground.asyncapi.io/
- update docu
- CBS support new spec (in the EventActivation query). This is a temporary solution so just support new spec and do not do any major refactoring.

**Comment by aerfio** [comment]
As I'm going on a holiday I'm going to list what is done and what is left to be done:
- [ ] support new styling and make sure it is consistent with other specs
    - [ ] make sure that OData component, AsyncAPI and Swagger have same details, like arrows in collapse buttons et cetera (consistency)

- [x] validator/parser as a props -> in a form of propagating props to asyncapi-parser
- [ ] remove styled-components and introduce 
- [x] improve error handling to not stop the rendering + display error in UI (have a flag to disable UI errors so we can not display them in the catalog/instance) -> in a form of a banner, we will not be parsing errors because it's too error-prone
- [ ] update docu -> everything done by me is documented
- [ ] remove playground from asyncapi-react and contribute -> do not remove playground in asyncapi-react (for dev purposes) but only contribute
- [x] support asyncapi spec 2.0.0-rc2 that is not yet released but we know will look like 
- [x] use https://github.com/asyncapi/parser-js to parse spec in UI
- [x] minimum is support for SAP specs

**Comment by aerfio** [comment]
There's only one little bug with https://raw.githubusercontent.com/asyncapi/asyncapi/master/examples/next/rpc-server.yml
![image](https://user-images.githubusercontent.com/17271979/63586382-7a134300-c5a1-11e9-87d9-c51e951d98c2.png)
